# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "" # blank # the website title (if blank, full name will be used instead)

---
layout: redirected
sitemap: false
permalink: /
redirect_to:  /itsme/
---